"""Create a baseline migrations

Revision ID: 1fdfbd00ff5f
Revises: 
Create Date: 2026-04-07 16:26:02.707947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fdfbd00ff5f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('height_cm', sa.Numeric(), nullable=True),
    sa.Column('weight_kg', sa.Numeric(), nullable=True),
    sa.Column('sex', sa.Enum('H', 'F', name='sex_enum'), nullable=True),
    sa.Column('has_sport_license', sa.Boolean(), nullable=True),
    sa.Column('education_level', sa.Enum('bac', 'bac+2', 'bac+3', 'master', 'doctorat', 'aucun', name='education_level_enum'), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('is_smoker', sa.Boolean(), nullable=True),
    sa.Column('is_french_national', sa.Boolean(), nullable=True),
    sa.Column('family_status', sa.Enum('marié', 'célibataire', 'divorcé', 'veuf', name='family_status_enum'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('loan_informations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('estimated_monthly_income', sa.Numeric(), nullable=True),
    sa.Column('credit_history_count', sa.Integer(), nullable=True),
    sa.Column('personal_risk_score', sa.Numeric(), nullable=True),
    sa.Column('credit_score', sa.Integer(), nullable=True),
    sa.Column('monthly_rent', sa.Numeric(), nullable=True),
    sa.Column('loan_amount', sa.Numeric(), nullable=True),
    sa.Column('account_created_at', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('loan_informations')
    op.drop_table('clients')
    # ### end Alembic commands ###
