"""Update relation type between clien & loan_information

Revision ID: d2dbed94dcd4
Revises: 1fdfbd00ff5f
Create Date: 2026-04-07 17:50:54.480391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2dbed94dcd4'
down_revision: Union[str, Sequence[str], None] = '1fdfbd00ff5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('loan_informations_client_id_key'), 'loan_informations', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('loan_informations_client_id_key'), 'loan_informations', ['client_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
