"""Add missing columns

Revision ID: d6d1b52859e1
Revises: d2dbed94dcd4
Create Date: 2026-04-07 18:03:48.623243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6d1b52859e1'
down_revision: Union[str, Sequence[str], None] = 'd2dbed94dcd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('date_of_birth', sa.Date(), nullable=True))
    op.add_column('clients', sa.Column('created_at', sa.Date(), nullable=True))
    op.add_column('loan_informations', sa.Column('created_at', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loan_informations', 'created_at')
    op.drop_column('clients', 'created_at')
    op.drop_column('clients', 'date_of_birth')
    # ### end Alembic commands ###
