"""Add new column to client table

Revision ID: fee240360de4
Revises: d6d1b52859e1
Create Date: 2026-04-09 23:19:23.978507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fee240360de4'
down_revision: Union[str, Sequence[str], None] = 'd6d1b52859e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('het', 'hom', name='sexual_orientation_enum').create(op.get_bind())
    op.add_column('clients', sa.Column('sexual_orientation', sa.Enum('het', 'hom', name='sexual_orientation_enum'), nullable=True))
    op.add_column('clients', sa.Column('caf_quotient', sa.Numeric(), nullable=True))
    op.add_column('clients', sa.Column('child_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'child_count')
    op.drop_column('clients', 'caf_quotient')
    op.drop_column('clients', 'sexual_orientation')
    sa.Enum('het', 'hom', name='sexual_orientation_enum').drop(op.get_bind())
    # ### end Alembic commands ###
